[variables]
NIXPACKS_PHP_VERSION = "8.4"
NIXPACKS_NODE_VERSION = "24"

[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_24", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
  "composer install --ignore-platform-req=php+ --no-dev --optimize-autoloader --no-interaction",
  "npm install --include=optional"
]

[phases.build]
cmds = ["npm run build"]